# Generated by Django 2.2 on 2020-08-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200823_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='statustext',
            new_name='status_text',
        ),
    ]
